### PR TITLE
feat(mini): README updates

### PR DESCRIPTION
**Pull request by leefaus**
Updated the README with a more specific, step by step installation guide.  Can I get someone to go through the install and see if I am missing anything? 

**RENDERED**
https://github.com/armory/mini-spinnaker/blob/installation-instructions/readme.md

cc:// @away168 @chadtripod

### CODE REVIEW

**Comment by chadtripod** [comment]
@leefaus @away168 I can go through the README / install

**Comment by chadtripod** [comment]
@leefaus I attempted the install in AWS and ran into an error.  I'm going to try the installer on a local ubuntu VM running on VMware fusion.  

- Deploy spin-gate
  Failure
- Deploy spin-rosco
  Failure
Problems in Global:
! ERROR Failed check for Namespace/spinnaker in null
The connection to the server 127.0.0.1:6443 was refused - did you specify the
  right host or port?



- This mission is too important for me to allow you to jeopardize
  it.
- Failed to deploy Spinnaker.
http://34.213.193.36
username: 'admin'
password: 'LH49/gOTnsAMRPM1dsDOgJ43MB0l6JcZvldu85Z2ASTT80IU'
+ create_hal_shortcut
+ sudo tee /usr/local/bin/hal
#!/bin/bash
POD_NAME=$(kubectl -n spinnaker get pod -l app=halyard -oname | cut -d'/' -f 2)
# echo $POD_NAME
set -x
kubectl -n spinnaker exec -it ${POD_NAME} -- hal $@
+ sudo chmod 755 /usr/local/bin/hal
ubuntu@ip-172-31-29-91:~/mini-spinnaker/scripts$

I see the port is open on the host and that the spinnaker namespace is created in the yaml so I'll debug further.

**Comment by justinrlee** [comment]
Oh apparently I need to fix some mergey stuff.  I'll do this this weekend.

**Comment by justinrlee** [comment]
Merged all content directly into master as a separate push.

**Pull request closed without merging**
